#!/usr/bin/env python3
"""Generate `lib/client.js` — the browser bundle this plugin ships.

The bundle is a plain CJS factory registered into the DSH page module loader
(`window.__ModuleLoader__.load`). That loader resolves ONLY the packages a
plugin declares in `dsh.client.inject`, so a bundle cannot `require` a sibling
file — everything it needs must be inlined. This generator therefore reads the
hand-written logic from `lib/client.template.js` and substitutes the Russian
dictionary into its `__DICTIONARY__` placeholder, producing the shippable
artifact.

    build/ru.json     composed translations (tools/build_ru.py)
    lib/client.template.js   source of truth for the bundle logic
    lib/client.js            generated artifact, committed

Usage:
    python3 tools/gen_dict_js.py [build/ru.json] [lib/client.js]
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLACEHOLDER = "__DICTIONARY__"


def render_dictionary(namespaces: dict[str, dict[str, str]]) -> str:
    """Render the dictionary as a deterministic, diff-friendly JS literal.

    No trailing comma is emitted, which keeps the literal valid JSON as well as
    valid JavaScript — that is what lets the bundle test recover and compare it.
    """
    lines = ["{"]
    for ns in sorted(namespaces):
        entries = json.dumps(
            namespaces[ns], ensure_ascii=False, sort_keys=True, separators=(",", ":")
        )
        lines.append(f"      {json.dumps(ns, ensure_ascii=False)}: {entries},")
    if len(lines) > 1:
        lines[-1] = lines[-1].rstrip(",")
    lines.append("    }")
    return "\n".join(lines)


def generate(dict_path: str, template_path: str, out_path: str) -> tuple[int, int, int]:
    """Render the bundle; returns (namespaces, keys, bytes written)."""
    with open(dict_path, encoding="utf-8") as fh:
        payload = json.load(fh)
    namespaces = payload.get("namespaces", payload)
    keys = sum(len(entries) for entries in namespaces.values())

    with open(template_path, encoding="utf-8") as fh:
        template = fh.read()
    if PLACEHOLDER not in template:
        raise SystemExit(f"{template_path}: missing {PLACEHOLDER} placeholder")

    banner = (
        "// Generated by tools/gen_dict_js.py from lib/client.template.js — "
        "do not edit by hand.\n"
        f"// {len(namespaces)} namespaces, {keys} keys.\n"
    )
    bundle = banner + template.replace(PLACEHOLDER, render_dictionary(namespaces))

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(bundle)
    return len(namespaces), keys, len(bundle.encode("utf-8"))


def main() -> int:
    dict_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "build", "ru.json")
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "lib", "client.js")
    template_path = os.path.join(HERE, "lib", "client.template.js")
    namespaces, keys, size = generate(dict_path, template_path, out_path)
    print(f"{out_path}: {namespaces} namespaces, {keys} keys, {size / 1024:.0f} KiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
